function H = plotCorrField(midx)

load tapering_matrix.mat; % currently this is generated by running RLM_MAC.
load inputData.mat;

if nargin < 1
    midx = 1;
end

nx = options.nx;
ny = options.ny;
actnumX = [zeros(1,ny);reshape(options.actnum,nx,ny)];
NaX = sum(actnumX(:));
F = actnumX;
F(F==0) = NaN;
F(F==1) = tapering_matrix(1:NaX,midx); %#ok<*NODEF>
F = F(2:end,:);
%F = reshape(F,options.dim);
x = [0,options.xL]*1000;
y = [0,options.yL]*1000;
F = flip(F,1);
H = imagesc(y,x,F);
set(H,'AlphaData',~isnan(F))
set(gca,'ydir','normal')
set(gca,'xtick',[])
set(gca,'ytick',[])
%xlabel('{\it \fontname{Latin Modern Math} x}  [mm]','fontSize',10);
%ylabel('{\it \fontname{Latin Modern Math} y}  [mm]','fontSize',10);

